name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p /home/drawinger/.ssh
        echo "${{ secrets.SSH_PRIVATE }}" > /home/drawinger/.ssh/id_rsa
        chmod 600 /home/drawinger/.ssh/id_rsa
        ssh-keyscan 82.148.19.97 >> /home/drawinger/.ssh/known_hosts
        # Здесь замените "" на ваше имя сервера

    - name: Deploy
      run: |
        # Здесь поместите команды для деплоя вашего проекта по SSH
        ssh root@82.148.19.97 "cd /opt/timer && git pull && source venv/bin/activate && pip install fastapi"
        # Здесь замените "user@yourserver.com" и путь к проекту на ваши данные

      env:
        SSH_PRIVATE: ${{ secrets.SSH_PRIVATE}}
