name: ci-cd

#on: push
 
# Тут можно конкретизировать ветку, а так все
on:
   push:

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Пометьте задачу как завершенную успешно после успешного выполнения
      - name: Mark as successful
        run: echo "Deployment successful"
