name: build

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!development'

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check files
        run: ls -la

#      - name: running linters
#        run: npm i && npm run lint-fix
