name: build

on: push
 
# Тут можно конкретизировать ветку, а так все
#on:
#   push:
#    branches:
#       - development 
#      - locify-github-actions

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check files
        run: ls -la123

#      - name: running linters
#        run: npm i && npm run lint-fix
